version: "3.0"

services:

  siamese-search-webapp:
    build: ./web
    depends_on:
      - elasticsearch
    ports:
      - "8000:8000"
    networks:
          - es-net

  elasticsearch:
    container_name: elasticsearch-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
    networks:
      - es-net
    hostname: elastic
    ports:
      - "9200:9200"

  logstash:
    container_name: logstash-container
    image: docker.elastic.co/logstash/logstash:7.17.10
    volumes:
          - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
          - ./logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml:ro,Z
          - ./logstash/pipelines:/usr/share/logstash/pipelines:ro,Z
          - ./logstash/data_for_index/Users.xml:/usr/share/logstash/data_for_index/Users.xml:rw,Z
          - ./logstash/data_for_index/Posts.xml:/usr/share/logstash/data_for_index/Posts.xml:rw,Z
          - ./logstash/data_for_index/Comments.xml:/usr/share/logstash/data_for_index/Comments.xml:rw,Z
          - ./logstash/data_for_index/PostLinks.xml:/usr/share/logstash/data_for_index/PostLinks.xml:rw,Z
# ############################################################################################
    environment:
#     PAGE variable is name of indexed dataset, so if will be used stck overflow in future...
#     needs to be changed to StackOverflow or something else (dsp, tex, cooking, english...)
      PAGE: dsp
# #############################################################################################
      ELASTICSEARCH_PORT: 9200
    networks:
      - es-net
    ports:
      - "5044:5044"
    depends_on:
      - elasticsearch


networks:
  es-net:
    driver: bridge